apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcep-api-deployment
  labels:
    environment: microservices
spec:
  selector:
    matchLabels:
      app: kcep-api
      environment: microservices
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kcep-api
        environment: microservices
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: kcep-api-container
          image: DOCKERIMAGE
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: kcepcreds
