#Values are base 64 encoded and will be decoded automatically by kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: kcepcreds
type: Opaque
data:
  KCEP_ORACLE_HOST: MTcyLjE2LjIwNy4xOTA=
  KCEP_ORACLE_PORT: MTUyMQ==
  KCEP_ORACLE_USER: S1VTRVI=
  KCEP_ORACLE_PASSWORD: bnhad0ZoS3V5eG5fbnh5dUtoRnda
  KCEP_ORACLE_SID: S0NFUA==
  KCEP_DB: S1VTRVI=
  KCEP_CMS_HOST: Y29wa2RuYXMtYzUtc2Nhbi5jby1vcGJhbmsuY28ua2U=
  KCEP_CMS_PORT: MTU2Mg==
  KCEP_CMS_USER: S0NFUFBPUlRBTA==
  KCEP_CMS_PASSWORD: WjJKZFR0Skh6Sm53dFQ1c0ExdE8j
  KCEP_CMS_SID: Q01TVEVTVA==
  KCEP_CMS_DB: S0NFUFBPUlRBTA==
  LDAP_SERVER_URL: bGRhcDovL3N2ZHJhZDAxLmNvLW9wYmFuay5jby5rZTozODkK
  LDAP_DOMAIN: Q08tT1BCQU5LLkNPLktFCg==
  PORTAL_URL: aHR0cDovLzE3Mi4xNi4yMTEuMjE6ODEK
  JWT_SECRET: QTQzN0NGNzRCRUQ5NUEzQjNCNkE0NzdENUY4MTQ=
  QUEUE_USER: Z3Vlc3QK
  QUEUE_PASS: Z3Vlc3QK
  PORT: MzAwMAo=
